# Generated by Django 4.1.2 on 2022-10-26 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_inquiry_instrument_review_teacher_delete_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='average_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
    ]
