# Generated by Django 4.1.2 on 2022-10-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_teacher_average_rating_alter_teacher_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
