# Generated by Django 4.1.2 on 2022-10-26 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_teacher_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='average_rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='main_app.instrument'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='years_experience',
            field=models.IntegerField(blank=True),
        ),
    ]
