# Generated by Django 4.1.2 on 2022-10-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_inquiry_availability_alter_inquiry_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
