# Generated by Django 4.1.2 on 2022-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_student_image_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
