# Generated by Django 4.1.2 on 2022-10-28 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepting_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instruments',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.instrument'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
