# Generated by Django 4.1.2 on 2022-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_inquiry_inquirer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
