# Generated by Django 4.1.2 on 2022-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_user_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instruments',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='main_app.instrument'),
        ),
    ]
