# Generated by Django 4.1.2 on 2022-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_user_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag_line',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
