# Generated by Django 4.1.2 on 2022-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_user_tag_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
